#pragma once

#include "NativeGameplayTags.h"

namespace GameplayTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_UI_Deck_Drag_Started);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_UI_Deck_Drag_Ended);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_UI_Collection_Notification);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_UI_DamageLog_Requested);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_Phase_Prepare_Completed);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_Phase_Changed);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_LaunchCount_Changed);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_ShiftCount_Changed);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_Party_Deployment_Started);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_Party_Launch_Requested);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_Party_Launch_Approved);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_Party_Launched);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_Party_AllBallsDead);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_Party_Shift_Requested);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_Dash_Requested);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_Dash_Approved);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_Skill_Use_Requested);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_Bumper_Triggered);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_Boss_Intro_Completed);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_Boss_Dead);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_UI_Choice_Exit);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TriggerEvent_Battle_Started);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TriggerEvent_Battle_PartyBuilt);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TriggerEvent_Battle_PartySwitched);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TriggerEvent_Battle_EnemyHit);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TriggerEvent_Battle_AfterDamage);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TriggerEvent_Battle_Revived);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TriggerEvent_Shop_Opened);
}
