#pragma once

#include "NativeGameplayTags.h"

namespace GameplayTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_UI_Deck_Drag_Started);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_UI_Deck_Drag_Ended);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_UI_Collection_Notification);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_UI_DamageLog_Requested);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_Phase_Prepare_Completed);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_Phase_Changed);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_LaunchCount_Changed);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_ShiftCount_Changed);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_Party_Deployment_Started);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_Party_Launch_Requested);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_Party_Launch_Approved);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_Party_Launched);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_Party_AllBallsDead);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_Party_Shift_Requested);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_Skill_Use_Requested);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Battle_Boss_Dead);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_UI_Choice_Exit);
}
