;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Event..UI.Choice.Exit",DevComment="")
+GameplayTagList=(Tag="Event.UI.Drag.Cancelled",DevComment="")
+GameplayTagList=(Tag="Event.UI.Drag.Dropped",DevComment="")
+GameplayTagList=(Tag="Event.UI.Drag.Moved",DevComment="")
+GameplayTagList=(Tag="Event.UI.Drag.Started",DevComment="")
+GameplayTagList=(Tag="Event.Boss.State.Idle",DevComment="")
+GameplayTagList=(Tag="Event.Boss.State.Pattern",DevComment="")
+GameplayTagList=(Tag="Event.Boss.State.Groggy",DevComment="")
+GameplayTagList=(Tag="Event.Boss.State.Enraged",DevComment="")
+GameplayTagList=(Tag="Event.Boss.State.Dead",DevComment="")
